### PR TITLE
Don't blur receiveText

### PR DESCRIPTION
**Pull request by chbw**
This is only a matter of taste. Personally, I really like to select/copy text on web pages.

### CODE REVIEW

**Comment by cdaller** [comment]
I am fully with you - the reason why I added the blur was that the user does not get confused where to type. Without blurring the readonly field gets focused by clicking in it, but the user cannot type.

What do you think?

**Comment by cdaller** [comment]
not sure why this pull request is closed now - the changes of not blurring were NOT merged, but github thinks so and closed this PR - strange

**Comment by chbw** [comment]
> Without blurring the readonly field gets focused by clicking in it, but the user cannot type.
> 
> What do you think?

Leave it as it is. I could totally see me getting confused by the textarea having the focus but being unable to type in it. 
If I change my mind, I will open another pull request. :wink: 

> not sure why this pull request is closed now - the changes of not blurring were NOT merged, but github thinks so and closed this PR - strange

This probably has to do with me messing up my branching game. This pull request is based on a commit that became part of the pwa branch. There, I reverted this commit later in the version history to have a clean (single purpose) diff. By merging the pwa branch you also merged this commit (along with it's reversion).
I should have branched off your main for pwa to avoid this.

**Comment by cdaller** [comment]
Ok, we'll see. a copy button could also help. but saving the result and loading it again does also the trick :-)

73 de OE6CHD

**Pull request merged**
